name: Pyre Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pyre-check:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
      - name: Checkout Torchrec
        uses: actions/checkout@v4
      - name: Install dependencies
        run: >
          VERSION=$(grep "version" .pyre_configuration | sed -n -e 's/.*\(0\.0\.[0-9]*\).*/\1/p')
          pip install torch --index-url https://download.pytorch.org/whl/nightly/cpu &&
          pip install fbgemm-gpu --index-url https://download.pytorch.org/whl/nightly/cpu &&
          pip install -r requirements.txt &&
          pip install pyre-check-nightly==$VERSION
      - name: Pyre check
        run: pyre check
